// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using size.Carrinho.Data.Context;

#nullable disable

namespace size.Carrinho.Data.Migrations
{
    [DbContext(typeof(CarrinhoContext))]
    partial class CarrinhoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Carrinho")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("size.Carrinho.Business.AggregateRoots.Carrinho", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AgregateId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InicioProcessamento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Carrinhos", "Carrinho");
                });

            modelBuilder.Entity("size.Carrinho.Business.Entities.Duplicata", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CarrinhoId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarrinhoId");

                    b.ToTable("Duplicatas", "Carrinho");
                });

            modelBuilder.Entity("size.Carrinho.Business.Entities.Duplicata", b =>
                {
                    b.HasOne("size.Carrinho.Business.AggregateRoots.Carrinho", "Carrinho")
                        .WithMany("Duplicatas")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");
                });

            modelBuilder.Entity("size.Carrinho.Business.AggregateRoots.Carrinho", b =>
                {
                    b.Navigation("Duplicatas");
                });
#pragma warning restore 612, 618
        }
    }
}
