// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using size.fichaCadastral.Data.Context;

#nullable disable

namespace size.fichaCadastral.Data.Migrations
{
    [DbContext(typeof(FichaCadastralContext))]
    partial class FichaCadastralContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("FichaCadastral")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("size.FichaCadastral.Business.AggregateRoots.Tomador", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tomadores", "FichaCadastral");
                });

            modelBuilder.Entity("size.FichaCadastral.Business.AggregateRoots.Tomador", b =>
                {
                    b.OwnsOne("size.Core.DomainObjects.ValueObjects.Documento", "Documento", b1 =>
                        {
                            b1.Property<string>("TomadorId")
                                .HasColumnType("varchar(200)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("varchar(200)")
                                .HasColumnName("Numero");

                            b1.Property<int>("Tipo")
                                .HasColumnType("int")
                                .HasColumnName("Tipo");

                            b1.HasKey("TomadorId");

                            b1.ToTable("Tomadores", "FichaCadastral");

                            b1.WithOwner()
                                .HasForeignKey("TomadorId");
                        });

                    b.Navigation("Documento")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
