// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using size.Operacao.Data.Context;

#nullable disable

namespace size.Operacao.Data.Migrations
{
    [DbContext(typeof(OperacaoContext))]
    partial class OperacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Operacao")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("size.Operacao.Business.AggregateRoots.Operacao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(200)")
                        .HasDefaultValueSql("CAST(NEXT VALUE FOR dbo.CodigoSequence AS VARCHAR(20))");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxaAntecipacao")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TomadorId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("ValorBruto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Operacoes", "Operacao");
                });

            modelBuilder.Entity("size.Operacao.Business.Entities.Duplicata", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OperacaoId")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OperacaoId");

                    b.ToTable("Duplicatas", "Operacao");
                });

            modelBuilder.Entity("size.Operacao.Business.Entities.Duplicata", b =>
                {
                    b.HasOne("size.Operacao.Business.AggregateRoots.Operacao", "Operacao")
                        .WithMany("Duplicatas")
                        .HasForeignKey("OperacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operacao");
                });

            modelBuilder.Entity("size.Operacao.Business.AggregateRoots.Operacao", b =>
                {
                    b.Navigation("Duplicatas");
                });
#pragma warning restore 612, 618
        }
    }
}
